openapi: 3.1.0
info:
  title: Officely - API documentation for Flatly
  version: 0.0.1
  description:  |
    Uses:
    1. view available filters
       - GET /filters
    2.  Make a booking
        1. Find a place to book
            - GET /offices?startDate=...&endDate=...&addr=...&maxDist=1000&sort=...&pageSize=10&pageToken=... -> list of offices with: distance, minPrice, maxPrice
            - GET /offices/{officeId}/offers?startDate=...&endDate=... -> list of offers with availability info, price info and cancellation info
        2. Create or find user
            1. Find user
                - GET /users?email=bob@example.com -> id: string
            2. Create user if not found
                - POST /users {email, firstName, lastName} -> id: string
        3. Create booking
            - POST /users/{userId}/bookings {officeId, offerId} -> bookingId: string
            - GET /users/{userId}/bookings/{bookingId} -> payment info (bank transfer), time left to pay, to cancel
        4. Cancel booking
            - POST /users/{userId}/bookings/{bookingId}/cancel
    3. View bookings
        1. Find user
            - GET /users?email=bob@example.com -> id: string
        2. Fetch booking list
            - GET /users/{id}/bookings -> list of bookings without details of offices and items
            - GET /offices/{officeId} -> office details
            - GET /offices/{officeId}/items/{itemId} -> item details

components: 
  schemas:
    PageSize:
      type: integer
      minimum: 1
      maximum: 50 # TODO: VALIDATE
      examples: [25]
    FilterElement:
      type: object
      properties: 
        key:
          type: string
        label:
          type: string
      oneOf: 
        - type: object
          properties: 
            type:
              type: string
              const: "flags"
            flags:
              type: array
              items:
                type: object
                properties:
                  key:
                    type: string
                  label:
                    type: string
            min:
              type: integer
            max:
              type: integer
        - type: object
          properties: 
            type:
              type: string
              const: "integer"
            min:
              type: integer
            max:
              type: integer
    FilterSection:
      type: object
      properties: 
        key:
          type: string
        label:
          type: string
        elements:
          type: array
          items: 
            $ref: '#/components/schemas/FilterElement'
    Filters:
      type: array
      items: 
        $ref: '#/components/schemas/FilterSection'
    OfficeResource:
      type: object
      required: 
        - id
        - name
        - description
        - address
        - photoUrls
        - contactEmail
        - contactPhone
        - _links
      properties: 
        id:
          type: string
        name:
          type: string
        description:
          type: string
        address:
          type: string
        photoUrls:
          type: array
          items:
            type: string
        contactEmail:
          type: string
        contactPhone:
          type: string
        _links:
          type: object
          required:
            - self
          properties:
            self:
              type: string
    OfficeSearchQueryDetails:
      type: object
      required: 
        - minPrice
        - maxPrice
        - distance
      properties:
        minPrice:
          type: number
        maxPrice:
          type: number
        distance:
          type: number
    OfficeOffer:
      type: object
      required:
        - id
        - name
        - totalPrice
        - freeCancellationHours
        - paymentHours
        - paymentHoursType
        - properties
        - _links
      properties: 
        id:
          type: string
        name:
          type: string
        totalPrice:
          type: integer
        freeCancellationHours:
          type: integer
          description:  The number of hours before a reservation starts when a user can cancel it for free
        paymentHours:
          type: integer
          description: "Depending on the paymentHoursType, either the amount of hours for payment after the booking was made, or the payment must be made x hours before the booking starts"
        paymentHoursType:
          type: string
          enum:
            - beforeStart
            - afterBooking
        properties:
          type: object
          additionalProperties: 
            type: string
        _links:
          type: object
          properties:
            accept:
              type: string
              description: "TODO: How?"
    OfficeItemResource:
      type: object
      required:
        - id
        - name
        - description
        - floor
        - room
        - photoUrls
        - _links
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        building:
          type: string
          description: Only present if office consists of multiple buildings
          examples:
            - "A"
        floor:
          type: string
          examples:
            - "3"
        room:
          type: string
          examples:
            - "311"
        photoUrls:
          type: array
          items:
            type: string
        _links:
          type: object
          required:
            - self
          properties:
            self:
              type: string
    UserResource:
      type: object
      required:
        - id
        - email
        - firstName
        - lastName
        - _links
      properties:
        id:
          type: string
          examples:
            - "2056"
        email:
          type: string
          examples:
            - bob.react@example.com
        firstName:
          type: string
          examples:
            - Bob
        lastName:
          type: string
          examples:
            - React
        _links:
          type: object
          required:
            - self
            - update
            - bookings
          properties:
            self:
              type: string
              examples:
                - "/users/2056"
            update:
              type: string
              examples:
                - "/users/2056"
            bookings:
              type: string
              examples:
                - "/users/2056/bookings"
    BookingResource:
      type: object
      required:
        - id
        - officeId
        - itemId
        - status
        - startDate
        - endDate
        - _links
      properties: 
        id:
          type: string
          examples:
            - "R2026"
        officeId:
          type: string
          examples:
            - "O2040"
        itemId:
          type: string
          examples:
          - "I2020"
        status:
          type: string
          enum:
            - active
            - cancelledByUser
            - cancelledByStaff
            - upcoming
            - past
        startDate:
          type: string
          examples:
            - "2026-01-06"
        endDate:
          type: string
          examples:
            - "2026-01-26"
        cancellationReason:
          type: string
        _links:
          type: object
          required:
            - self
            - office
            - item
          properties:
            self:
              type: string
            office:
              type: string
            item:
              type: string
            cancel:
              type: string

tags:
  - name: filters
  - name: offices
  - name: users
  - name: bookings

paths:
  '/filters':
    get:
      tags: 
        - filters
      summary: Get a list of all filters
      responses: 
        "200":
          description: Success
          content: 
            application/json:
              schema: 
                type: object
                properties:
                  filters:
                    $ref: '#/components/schemas/Filters'
                  _links:
                    type: object
                    properties:
                      self:
                        type: string
                        examples:
                          - '/filters'
  '/offices':
    get:
      tags:
        - offices
      summary: Search for offices
      parameters:
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            examples:
              - "2026-01-06"
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            examples:
              - "2026-01-26"
        - name: nearAddress
          in: query
          required: true
          schema:
            type: string
        - name: maxDistanceFromAddress
          in: query
          required: true
          schema:
            type: integer
            description: In meters
            examples:
              - 5000
        - name: filter
          in: query
          schema: 
            type: array
            items:
              type: string
              examples:
                - "builtin.price.min:40"
                - "desk.type.standing:true"
        - name: pageSize
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/PageSize'
        - name: pageToken
          in: query
          schema:
            type: string
      responses: 
        "200":
          description: Success
          content:
            application/json: 
              schema:
                type: object
                required: 
                  - _pagination
                  - _links
                  - results
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      required: 
                        - office
                        - query
                        - _links
                      properties:
                        office:
                          $ref: '#/components/schemas/OfficeResource'
                        query:
                          $ref: '#/components/schemas/OfficeSearchQueryDetails'
                        _links:
                          type: object
                          required:
                            - offers
                          properties:
                            offers:
                              type: string
                  _pagination:
                    type: object
                    required: 
                      - currentPage
                      - lastPage
                      - pageSize
                    properties:
                      currentPage:
                        type: integer
                      lastPage:
                        type: integer
                      pageSize:
                        type: integer
                  _links:
                    type: object
                    required:
                      - self
                      - first
                      - last
                    properties:
                      self:
                        type: string
                      next:
                        type: string
                      prev:
                        type: string
                      first:
                        type: string
                      last:
                        type: string
  '/offices/{officeId}':
    get: 
      tags: ['offices']
      summary: "Get office details"
      parameters: 
        - name: officeId
          in: path
          required: true
          schema:
            type: string
      responses: 
        "200":
          description: Success
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/OfficeResource'
  '/offices/{officeId}/offers':
    get: 
      tags: ['offices']
      summary: "Get available items for booking"
      parameters: 
        - name: officeId
          in: path
          required: true
          schema:
            type: string
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            examples:
              - "2026-01-06"
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            examples:
              - "2026-01-26"
        - name: filter
          in: query
          schema: 
            type: array
            items:
              type: string
              examples:
                - "builtin.price.min:40"
                - "desk.type.standing:true"
      responses: 
        "200":
          description: Success
          content: 
            application/json: 
              schema: 
                type: object
                properties:
                  offers:
                    type: array
                    items:
                      $ref: '#/components/schemas/OfficeOffer'
                  _links:
                    type: object
                    properties:
                      self:
                        type: string
  '/offices/{officeId}/items/{itemId}':
    get: 
      tags: ['offices']
      summary: "Get office item details"
      parameters: 
        - name: officeId
          in: path
          required: true
          schema:
            type: string
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      responses: 
        "200":
          description: Success
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/OfficeItemResource'
  '/users':
    get:
      tags: ['users']
      summary: Get user by email
      parameters:
      - name: email
        in: query
        required: true
        schema:
          type: string
          examples:
            - bob.react@example.com
      responses: 
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                maxItems: 1
                minItems: 0
                items:
                  $ref: '#/components/schemas/UserResource'
    post:
      tags: ['users']
      summary: Create user
      requestBody:
        required: true
        content: 
          application/json: 
            schema: 
              type: object
              properties: 
                email:
                  type: string
                  examples:
                    - bob.react@example.com
                firstName:
                  type: string
                  examples:
                    - Bob
                lastName:
                  type: string
                  examples:
                    - React
      responses: 
        "201":
          description: Created
          headers: 
            Location:
              examples:
                - /users/2056
              description: URL to the newly created user (for example /users/2056)
              schema: 
                type: string
        "400":
          description: "Validation error TODO: describe body!"
        "409":
          description: "User with that email already exists"
  '/users/{userId}/bookings':
    get:
      tags: ['bookings']
      summary: "Get an user's bookings"
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
          examples:
            - 2056
      - name: pageSize
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/PageSize'
      - name: pageToken
        in: query
        schema:
          type: string
      responses:
        "200":
          description: Success
          content: 
            application/json: 
              schema: 
                type: object
                required:
                  - bookings
                  - _pagination
                  - _links
                properties:
                  bookings:
                    type: array
                    items:
                      $ref: '#/components/schemas/BookingResource'
                  _pagination:
                    type: object
                    required: 
                      - currentPage
                      - lastPage
                      - pageSize
                    properties:
                      currentPage:
                        type: integer
                      lastPage:
                        type: integer
                      pageSize:
                        type: integer
                  _links:
                    type: object
                    required:
                      - self
                      - first
                      - last
                    properties:
                      self:
                        type: string
                      next:
                        type: string
                      prev:
                        type: string
                      first:
                        type: string
                      last:
                        type: string
  '/users/{userId}/bookings/{bookingId}/cancel':
    post:
      tags: ['bookings']
      summary: "Cancel a booking"
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
          examples:
            - 2056
      - name: bookingId
        in: path
        required: true
        schema:
          type: string
          examples:
            - 2056
      responses:
        "200":
          description: Success
          