spring:
  datasource:
    url: jdbc:mysql://localhost:3306/officely?serverTimezone=UTC
    username: officely
    password: officely123
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
    show-sql: false
    generate-ddl: true
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update
  hateoas:
    use-hal-as-default-json-media-type: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 250MB

cors:
  origins: '*'

flatly:
  token: abc

mail:
  from: "Officely <system@officely.noscorp.pl>"
  host: "mail.noscorp.pl"
  domain-whitelist:
    - noscorp.pl