name: Publish preview update

on:
  push:
    branches: ["main"]
    paths:
      - "frontend-mobile/**"

jobs:
  publish_dev_update:
    name: Publish dev update
    type: update
    environment: preview
    params:
      branch: main-preview
